services:
    sonata.admin.module:
        class: philemon\ModuleBundle\Admin\ModuleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Module" }
        arguments:
            - ~
            - philemon\ModuleBundle\Entity\Module
            - ~
        calls:
            - [ setTranslationDomain, [philemonModuleBundle]]
    sonata.admin.activity:
        class: philemon\ModuleBundle\Admin\ActivityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Activity" }
        arguments:
            - ~
            - philemon\ModuleBundle\Entity\Activity
            - ~
        calls:
            - [ setTranslationDomain, [philemonModuleBundle]]
    sonata.admin.bareme:
        class: philemon\ModuleBundle\Admin\BaremeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Bareme" }
        arguments:
            - ~
            - philemon\ModuleBundle\Entity\Bareme
            - ~
        calls:
            - [ setTranslationDomain, [philemonModuleBundle]]
