philemon_module_homepage:
    pattern:  /module
    defaults: { _controller: philemonModuleBundle:Module:index }

philemon_module_show:
    pattern: /module/show/{id}
    defaults: { _controller: philemonModuleBundle:Module:show, id:default }

philemon_module_register:
    pattern: /module/register/{module_id}
    defaults: { _controller: philemonModuleBundle:Module:register, module_id:default }

philemon_module_unregister:
    pattern: /module/unregister/{module_id}
    defaults: { _controller: philemonModuleBundle:Module:unregister, module_id:default }

philemon_activity_show:
    pattern: /module/activity/{activity_id}
    defaults: { _controller: philemonModuleBundle:Module:activity, activity_id:default }

philemon_activity_show_resume:
    pattern: /module/activityResume/{activity_id}
    defaults: { _controller: philemonModuleBundle:Module:activity, activity_id:default }

philemon_activity_unregister:
    pattern: /module/activity/unregister/{activity_id}
    defaults: { _controller: philemonModuleBundle:Module:unregister_activity, activity_id:default }

philemon_activity_register:
    pattern: /module/activity/register/{activity_id}
    defaults: { _controller: philemonModuleBundle:Module:register_activity, activity_id:default }

philemon_learning_homepage:
    pattern: /learning
    defaults: { _controller: philemonModuleBundle:Learning:index }

philemon_learning_show:
    pattern: /learning/show/{activity_id}
    defaults: { _controller: philemonModuleBundle:Learning:show, activity_id:default }

philemon_bareme_index:
    pattern: /correction/{activity_id}
    defaults: { _controller: philemonModuleBundle:Module:corr, activity_id:default }

philemon_rate:
    pattern: /rate/{activity_id}/{corrector}
    defaults: { _controller: philemonModuleBundle:Module:rate, activity_id:default, corrector:default }

philemon_ratev:
    pattern: /rate_notation/{activity_id}/{use}
    defaults: { _controller: philemonModuleBundle:Module:ratev, activity_id:default, use:default }

philemon_find_peer:
    pattern: /correction/find/{activity_id}
    defaults: { _controller: philemonModuleBundle:Module:peer, activity_id:default}


