<?php

namespace Recowin\CalendarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CorrectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
}
