parameters:
#    philemon_user.example.class: philemon\UserBundle\Example

services:
#    philemon_user.example:
#        class: %philemon_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
