parameters:
#    philemon_ft_calendar.example.class: philemon\FtCalendarBundle\Example

services:
#    philemon_ft_calendar.example:
#        class: %philemon_ft_calendar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
