philemon_trombi:
    pattern: /trombi
    defaults: { _controller:philemonTrombiBundle:Default:index }

philemon_trombi_null:
    pattern: /trombi/
    defaults: { _controller:philemonTrombiBundle:Default:index }

philemon_trombi_spe:
    pattern:  /trombi/{name}
    defaults: { _controller: philemonTrombiBundle:Listing:show, name:default}
