philemon_module:
    resource: "@philemonModuleBundle/Resources/config/routing.yml"
    prefix:   /

philemon_ldap:
    resource: "@philemonLdapBundle/Resources/config/routing.yml"
    prefix:   /

philemon_home:
    resource: "@philemonHomeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

CCDNForumForumBundle:
    resource: "@CCDNForumForumBundle/Resources/config/routing.yml"

ccdn_homepage:
    pattern: /forum
    defaults: { _controller: CCDNForumForumBundle:UserCategory:index, _locale: en, forumName: default }

hackzilla_ticket:
    resource: "@HackzillaTicketBundle/Resources/config/routing.yml"
    prefix:   /
